name: realsense

dependencies:
  - python=3.6
  - pip
  - pip:
    - beautifulsoup4
    - black
    - flake8
    - jupyter
    - labelImg
    - numpy
    - matplotlib
    - pandas
    - pyrealsense2
    - pypng
    - rope
    - untangle
    - xmltodict
